name: Deploy to GitHub Pages

on:
  # 每次推送到 master 分支时触发
  push:
    branches: [master]
  
  # 也允许手动触发
  workflow_dispatch:

permissions:
  contents: read # 读取仓库内容
  pages: write # 写入github pages
  id-token: write # 写入身份令牌

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 不是必需的，但有助于获取完整的 git 历史
      
      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          cache: pnpm # 或者 yarn, pnpm 根据你使用的包管理器调整

      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Install dependencies
        run: pnpm install # 或者 npm install, yarn install, pnpm install
      
      - name: Build with VitePress
        run: pnpm run docs:build # 根据你的 package.json 脚本调整
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build # 需要build执行结束
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4